### ISSUE TITLE
Unable to load planets.

### ISSUE THREAD

**Issue by JoshoSarma** [GregroxMun/2W2PJ#4]
Having installed a lot of mods including PJ2, Niako's Heightmap, Kopernicus, Kopernicus Expansion, EVE and Scatterer, I was disappointed to read an error message from Kopernicus telling me that it was unable to load PJ2. This is my first time installing PJ2.
I again tried to load the game with no mods but PJ2, its dependencies and their dependencies. The same error message appeared again, indicating that this is an error with one of the 5 mods listed above.
Please find attached KSP.log.
Issue has also been reported by me and one other user in the forum thread.
[KSP.log](https://github.com/GregroxMun/2W2PJ/files/11358730/KSP.log)

**Comment by WhirligigGirl** [comment]
What operating system are you on? If you're on Linux (maybe also Mac?) there's some filepath problems in the release version that arent an issue on windows but are on linux. (\ when there should only be /) IIRC they should be fixed on the github main version.

make sure you have installed PJ2 correctly, i.e., you have a folder GameData/PJ2 and not a folder something like GameData/PlanetJam2/GameData/PJ2 or something like that. I assume you also have Kopernicus' prereqs too.

Also make sure you're using the modern version of Kopernicus Expansions Continued from vabienArt and not the like, CKAN version. Also, I see there is a new update to that version of KopX, so another thing you could try is to backdate to the June 15 2021 version which PJ2 was developed on.

I suppose it's possible it could be a problem introduced in a Kopernicus update. one thing you might try to test that is to use the version recommended in the forum thread (iirc it's release-141) and see if that changes anything.

**Comment by JoshoSarma** [comment]
I used the version of Kopernicus Expansions Continued from June 15 2021, and it's now working. [At least Armstrong is showing up rather than Kerbin; haven't played enough to spot any other bugs]. Sorry, I have no ideas why as I am fairly bad at coding. My KSP.log is attached above though.
Thank you very much for your advice & for organising and maintaining this amazing mod.
